#!/usr/bin/python3
# syslog-bridge: copy syslog datagrams received on /dev/log to stdout, one line per message,
# so that syslog() calls (asperanoded local2, ascp, asconfigurator...) appear in container logs.
import os
import re
import socket
import sys

SOCKET_PATH = '/dev/log'
PRIORITY = re.compile(rb'^<\d{1,3}>')

try:
    os.unlink(SOCKET_PATH)
except FileNotFoundError:
    pass
sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
sock.bind(SOCKET_PATH)
# Non-root daemons (asperadaemon) must be able to log
os.chmod(SOCKET_PATH, 0o666)

while True:
    message = PRIORITY.sub(b'', sock.recv(65536)).rstrip(b'\n')
    sys.stdout.buffer.write(message + b'\n')
    sys.stdout.buffer.flush()
